### PR TITLE
Fullscreen.js (Deutsch+Turkish) Translation

### PR DESCRIPTION
**Pull request by SupLiCatinG**
Includes some corrections for Deutsch, thanks to  @SIMULATAN.

### CODE REVIEW

**Review by daksh2k — APPROVED** [review]
Looks good, thanks!

**Comment by SupLiCatinG** [comment]
Sorry for creating problem, with added languages extension doesnt inject to spicetify.

**Comment by daksh2k** [comment]
It's working fine on my end, what error are you facing?

Also, this is temporary I am currently in the middle of rewriting the entire extension using `spicetify-creator` which will allow for code splitting into different files so each language will have a separate file, for eg, `en-US.json`, `de-DE.json` etc.,

I'll also make a Crowdin project to make contributions to translations easier.

**Comment by SupLiCatinG** [comment]
I can't see buttons related to FullScreen also keyboard shortcuts doesnt work. 
I am on 
image

**Comment by SupLiCatinG** [comment]
image

**Comment by daksh2k** [comment]
Replace the file from there with the file from this repo, then run `spicetify -e update`.

Also try via marketplace?

**Comment by SupLiCatinG** [comment]
image
Marketplace didn't solved either. I think something mismatches somepoint, because i'm on older version. Gotta try newer versions on freetime. Thanks.

**Comment by SupLiCatinG** [comment]
Re-installing everything solved, thanks for help.

**Pull request merged**
